@startuml sequence_diagram

' Define the background color
'skinparam backgroundColor #EBF72B

skinparam backgroundColor #LightGoldenRodYellow

actor User as u #Red/Yellow

'actor User as u #Red/LightGreen

participant "Frontend(Angular/React)" as FE

box #LightSeaGreen
'box #LightGreen

participant "Backend(Java/Spring Boot)" as BE

database "DataBase(Mysql)" as DB #Gainsboro
end box

participant "Cirro Platform" as CP #MediumAquaMarine
'participant "Cirro Platform" as CP #AAFAC9



u -> FE: <color:Blue> Send Request to get a SPA

FE-> BE:Request Rest API call

BE -> BE:Internal computation

BE -> DB:storage specific space data

DB --> BE:recover specific space data

BE -> CP:Request API call

CP --> BE:Response API

BE --> FE:Rest API response

FE --> u: <color:Blue> Response


@enduml